/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as NewsRouteImport } from './routes/news'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as ConstructorsRouteImport } from './routes/constructors'
import { Route as CircuitsRouteImport } from './routes/circuits'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicNewsRouteImport } from './routes/api/public/news'

const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructorsRoute = ConstructorsRouteImport.update({
  id: '/constructors',
  path: '/constructors',
  getParentRoute: () => rootRouteImport,
} as any)
const CircuitsRoute = CircuitsRouteImport.update({
  id: '/circuits',
  path: '/circuits',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNewsRoute = ApiPublicNewsRouteImport.update({
  id: '/api/public/news',
  path: '/api/public/news',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/circuits': typeof CircuitsRoute
  '/constructors': typeof ConstructorsRoute
  '/drivers': typeof DriversRoute
  '/news': typeof NewsRoute
  '/statistics': typeof StatisticsRoute
  '/api/public/news': typeof ApiPublicNewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/circuits': typeof CircuitsRoute
  '/constructors': typeof ConstructorsRoute
  '/drivers': typeof DriversRoute
  '/news': typeof NewsRoute
  '/statistics': typeof StatisticsRoute
  '/api/public/news': typeof ApiPublicNewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/circuits': typeof CircuitsRoute
  '/constructors': typeof ConstructorsRoute
  '/drivers': typeof DriversRoute
  '/news': typeof NewsRoute
  '/statistics': typeof StatisticsRoute
  '/api/public/news': typeof ApiPublicNewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/circuits'
    | '/constructors'
    | '/drivers'
    | '/news'
    | '/statistics'
    | '/api/public/news'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/circuits'
    | '/constructors'
    | '/drivers'
    | '/news'
    | '/statistics'
    | '/api/public/news'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/circuits'
    | '/constructors'
    | '/drivers'
    | '/news'
    | '/statistics'
    | '/api/public/news'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  CircuitsRoute: typeof CircuitsRoute
  ConstructorsRoute: typeof ConstructorsRoute
  DriversRoute: typeof DriversRoute
  NewsRoute: typeof NewsRoute
  StatisticsRoute: typeof StatisticsRoute
  ApiPublicNewsRoute: typeof ApiPublicNewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constructors': {
      id: '/constructors'
      path: '/constructors'
      fullPath: '/constructors'
      preLoaderRoute: typeof ConstructorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circuits': {
      id: '/circuits'
      path: '/circuits'
      fullPath: '/circuits'
      preLoaderRoute: typeof CircuitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/news': {
      id: '/api/public/news'
      path: '/api/public/news'
      fullPath: '/api/public/news'
      preLoaderRoute: typeof ApiPublicNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  CircuitsRoute: CircuitsRoute,
  ConstructorsRoute: ConstructorsRoute,
  DriversRoute: DriversRoute,
  NewsRoute: NewsRoute,
  StatisticsRoute: StatisticsRoute,
  ApiPublicNewsRoute: ApiPublicNewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
